name: grit-npm-check
on: 'push'
jobs:
  download:
    name: check-download
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: clone code
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: download grit
        run: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -- -y
      - name: --help
        run: |
          rustup --help
